# yaml-language-server: $schema=../data/schemas/json/config.json
---
log:
  filename: log/analysis.log
input_api:
  url: ""
  token: ""
output_api:
  url: ""
  token: ""
proxy_dict:
  http: ""
  https: ""
  ftp: ""
use_proxy: false
graph:
  height: 8
  width: 10
