# yaml-language-server: $schema=../schemas/json/config.json
---
log:
  filename: log/analysis.log
input_api:
  url: ""
  token: ""
output_api:
  url: ""
  token: ""
proxy_dict:
  http: ""
  https: ""
  ftp: ""
use_proxy: false
graph:
  height: 8
  width: 10
minio:
  url: localhost:9000
  access_key: my_key
  secret_key: my_secret
  secure: false
