# yaml-language-server: $schema=../schemas/json/config.json
---
PYDRODELTA_DIR: /home/user/pydrodelta
log:
  filename: pydrodelta.log
input_api:
  url: https://alerta.ina.gob.ar/test
  token: MY_TOKEN
output_api:
  url: https://alerta.ina.gob.ar/test
  token: MY_TOKEN
use_proxy: false
graph:
  height: 10
  width: 14
  